server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: HUANGfu0110
    url: jdbc:mysql://cdb-obych0ne.bj.tencentcdb.com:10214/zanzan?serverTimezone=UTC

mybatis:
  mapper-locations: classpath*:mapping/*.xml